#pragma once

#define C4PKG_VERSION_MAJOR 1
#define C4PKG_VERSION_MINOR 0
#define C4PKG_VERSION_PATCH 0

#define C4PKG_VERSION_STRING \
  "c4pkg " #C4DROID_VERSION_MAJOR "." #C4PKG_VERSION_MINOR "." #C4PKG_VERSION_PATCH
